# generated by datamodel-codegen:
#   filename:  1.json
#   timestamp: 2025-10-27T19:14:58+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Result(BaseModel):
    numero_fiche: str
    numero_version: int
    nature_juridique_rappel: str
    categorie_produit: str
    sous_categorie_produit: str
    marque_produit: str
    modeles_ou_references: str
    identification_produits: str
    conditionnements: Optional[str]
    date_debut_commercialisation: Optional[str]
    date_date_fin_commercialisation: Optional[str]
    temperature_conservation: Optional[str]
    marque_salubrite: Optional[str]
    informations_complementaires: Optional[str]
    zone_geographique_de_vente: str
    distributeurs: str
    motif_rappel: str
    risques_encourus: str
    preconisations_sanitaires: Optional[str]
    description_complementaire_risque: Optional[str]
    conduites_a_tenir_par_le_consommateur: str
    numero_contact: Optional[str]
    modalites_de_compensation: str
    date_de_fin_de_la_procedure_de_rappel: Optional[str]
    informations_complementaires_publiques: Optional[str]
    liens_vers_les_images: str
    lien_vers_la_liste_des_produits: Optional[str]
    lien_vers_la_liste_des_distributeurs: Optional[str]
    lien_vers_affichette_pdf: str
    lien_vers_la_fiche_rappel: str
    rappel_guid: str
    date_publication: str
    libelle: str
    id: int


class Model(BaseModel):
    total_count: int
    results: List[Result]
