# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2025-10-27T17:57:36+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class ResultEntry(BaseModel):
    numero_fiche: str
    numero_version: int
    nature_juridique_rappel: str
    categorie_produit: str
    sous_categorie_produit: str
    marque_produit: str
    modeles_ou_references: str
    identification_produits: str
    conditionnements: str
    date_debut_commercialisation: str
    date_date_fin_commercialisation: None
    temperature_conservation: str
    marque_salubrite: None
    informations_complementaires: None
    zone_geographique_de_vente: str
    distributeurs: str
    motif_rappel: str
    risques_encourus: str
    preconisations_sanitaires: None
    description_complementaire_risque: None
    conduites_a_tenir_par_le_consommateur: str
    numero_contact: str
    modalites_de_compensation: str
    date_de_fin_de_la_procedure_de_rappel: str
    informations_complementaires_publiques: None
    liens_vers_les_images: str
    lien_vers_la_liste_des_produits: str
    lien_vers_la_liste_des_distributeurs: str
    lien_vers_affichette_pdf: str
    lien_vers_la_fiche_rappel: str
    rappel_guid: str
    date_publication: str
    libelle: str
    id: int


class Model(BaseModel):
    total_count: int
    results: List[ResultEntry]
